// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcwohN2njSe9Oy6ifSzBvbCF7wPl2KawA',
    appId: '1:170374734047:web:51cb3098ca540c789c496a',
    messagingSenderId: '170374734047',
    projectId: 'flutter-ecommerce-hahaha',
    authDomain: 'flutter-ecommerce-hahaha.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-hahaha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADBMZCAW-zPp99J_TEwpiS_wuaoBt1SAQ',
    appId: '1:170374734047:android:f7de5dada0b973a69c496a',
    messagingSenderId: '170374734047',
    projectId: 'flutter-ecommerce-hahaha',
    storageBucket: 'flutter-ecommerce-hahaha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlldQ8oer62NnMqAcSHbbGbHZyK9781Q',
    appId: '1:170374734047:ios:1bd7f0b589a3424d9c496a',
    messagingSenderId: '170374734047',
    projectId: 'flutter-ecommerce-hahaha',
    storageBucket: 'flutter-ecommerce-hahaha.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlldQ8oer62NnMqAcSHbbGbHZyK9781Q',
    appId: '1:170374734047:ios:6cda42c9f572dbb49c496a',
    messagingSenderId: '170374734047',
    projectId: 'flutter-ecommerce-hahaha',
    storageBucket: 'flutter-ecommerce-hahaha.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
